package main;

import com.formdev.flatlaf.FlatLightLaf;
import functions.Client;
import functions.IpAPI;
import functions.Method;
import functions.MutexDeployer;
import java.awt.AWTException;
import java.awt.Color;
import java.awt.Image;
import java.awt.MenuItem;
import java.awt.PopupMenu;
import java.awt.SystemTray;
import java.awt.Toolkit;
import java.awt.TrayIcon;
import java.awt.event.ActionEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.net.BindException;
import java.net.ServerSocket;
import java.net.URL;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Properties;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import menubar.about_form;

/*
 * The MIT License
 *
 * Copyright 2021 Neeraj.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
/**
 *
 * @author Neeraj
 */
public class ServerMain extends javax.swing.JFrame
{
    private static final long serialVersionUID = 5455364458445364L;
    private int port = 0;
    private boolean isReadyToClose;
    private boolean isAlreadyLoaded = false;

    public ServerMain()
    {
        try
        {
            //will set the default installed l&F as windows Native
            // UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            UIManager.setLookAndFeel(new FlatLightLaf());
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            initComponents();
            initComponentsNew();
            this.setIconImage(new ImageIcon(getClass().getResource("/icons/main_icon.png")).getImage());
            date_now.setText(DateTimeFormatter.ofPattern("dd-MM-yyyy").format(LocalDateTime.now()));
            Timer timer = new Timer();
            TimerTask task = new TimerTask()
            {
                @Override
                public void run()
                {
                    time_now.setText(DateTimeFormatter.ofPattern("hh:mm:ss a").format(LocalDateTime.now()));
                }
            };
            timer.scheduleAtFixedRate(task, 1000, 1000);
            CurrStatus.append("------------------------------------------------[Started]-------------------------------------------------\n");
            dirVerifier();
        }
        catch(Exception ex)
        {
            Logger.getLogger(ServerMain.class.getName()).log(Level.SEVERE, null, ex);
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        portNumber = new javax.swing.JLabel();
        StartBtn = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        portField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        activeUsers = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        public_Ip_Port = new javax.swing.JTextField();
        loc_Ip_Port = new javax.swing.JTextField();
        refreshBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        serverStatus = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        StopBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        CurrStatus = new javax.swing.JTextArea();
        date_now = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        time_now = new javax.swing.JLabel();
        mutexCheckbox = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        info_menu = new javax.swing.JMenu();
        logging_info = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        onCloseMenu = new javax.swing.JMenu();
        menuHide = new javax.swing.JCheckBoxMenuItem();
        menuExit = new javax.swing.JCheckBoxMenuItem();
        aboutMenu = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("CodyNeeraj's Socketty");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(SystemFontLoader.getSegoe_UIFont().deriveFont(0, 14f));
        jLabel1.setText("Selected IP");

        portNumber.setFont(SystemFontLoader.getSegoe_UIFont().deriveFont(0, 14f));
        portNumber.setText("Enter Port");

        StartBtn.setBackground(new java.awt.Color(0, 204, 0));
        StartBtn.setFont(SystemFontLoader.getSegoe_UIFont().deriveFont(0, 18f));
        StartBtn.setText("Start");
        StartBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                StartBtnActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setText("Localhost (127.0.0.1)");
        jTextField1.setToolTipText("Default");

        portField.setToolTipText("Enter only integers between given range");
        portField.addAncestorListener(new javax.swing.event.AncestorListener()
        {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt)
            {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt)
            {
                portFieldAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt)
            {
            }
        });

        jLabel3.setFont(SystemFontLoader.getSegoe_UI_SemiBoldFont().deriveFont(0, 12f));
        jLabel3.setText("(10-65535)");
        jLabel3.setToolTipText("");

        jLabel4.setFont(SystemFontLoader.getSegoe_UI_SemiBoldFont().deriveFont(1, 15f));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Configuration");

        activeUsers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));

        public_Ip_Port.setEditable(false);
        public_Ip_Port.setFont(SystemFontLoader.getSegoe_UIFont().deriveFont(0, 11f));
        public_Ip_Port.setText("Loading...");

        loc_Ip_Port.setEditable(false);
        loc_Ip_Port.setFont(SystemFontLoader.getSegoe_UIFont().deriveFont(0, 11f));
        loc_Ip_Port.setText("Loading...");
        loc_Ip_Port.addAncestorListener(new javax.swing.event.AncestorListener()
        {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt)
            {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt)
            {
                loc_Ip_PortAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt)
            {
            }
        });

        refreshBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refresh.png"))); // NOI18N
        refreshBtn.setToolTipText("Refresh");
        refreshBtn.setEnabled(false);
        refreshBtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refresh_clicked.png"))); // NOI18N
        refreshBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                refreshBtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(SystemFontLoader.getSegoe_UIFont().deriveFont(0, 12f));
        jLabel5.setText("Local IP :");

        jLabel6.setFont(SystemFontLoader.getSegoe_UIFont().deriveFont(0, 12f));
        jLabel6.setText("Public IP :");

        jLabel10.setFont(SystemFontLoader.getSegoe_UIFont().deriveFont(0, 12f));
        jLabel10.setText("Current Status");

        serverStatus.setFont(SystemFontLoader.getSegoe_UIFont().deriveFont(0, 12f));
        serverStatus.setForeground(new java.awt.Color(255, 0, 0));
        serverStatus.setText("Not Running..");

        jLabel12.setFont(SystemFontLoader.getSegoe_UIFont().deriveFont(0, 12f));
        jLabel12.setText("Active Clients");

        StopBtn.setBackground(new java.awt.Color(255, 153, 153));
        StopBtn.setFont(SystemFontLoader.getSegoe_UIFont().deriveFont(0, 17f));
        StopBtn.setText("Stop");
        StopBtn.setEnabled(false);
        StopBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                StopBtnActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setFont(SystemFontLoader.getMicrosoft_SS_Font().deriveFont(0, 11f));
        jScrollPane1.setOpaque(false);

        CurrStatus.setEditable(false);
        CurrStatus.setColumns(20);
        CurrStatus.setFont(SystemFontLoader.getSegoeUI_SymbolFont().deriveFont(0, 11f));
        CurrStatus.setLineWrap(true);
        CurrStatus.setRows(5);
        CurrStatus.setTabSize(4);
        CurrStatus.setWrapStyleWord(true);
        CurrStatus.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        CurrStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(CurrStatus);

        date_now.setFont(SystemFontLoader.getSegoeUI_SymbolFont().deriveFont(0, 11f));
        date_now.setForeground(new java.awt.Color(0, 0, 255));

        jLabel8.setFont(SystemFontLoader.getSegoeUI_SymbolFont().deriveFont(0, 11f));
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText(" Date-Time ::");

        time_now.setFont(SystemFontLoader.getSegoeUI_SymbolFont().deriveFont(0, 11f));
        time_now.setForeground(new java.awt.Color(0, 0, 255));

        mutexCheckbox.setFont(SystemFontLoader.getSegoe_UI_SemiBoldFont().deriveFont(0, 11f));
        mutexCheckbox.setSelected(true);
        mutexCheckbox.setText("Mutex Locking");
        mutexCheckbox.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                mutexCheckboxItemStateChanged(evt);
            }
        });

        jMenu1.setText("Options");

        info_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/info_icon.png"))); // NOI18N
        info_menu.setText("Info");

        logging_info.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.SHIFT_MASK));
        logging_info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/log_menu.png"))); // NOI18N
        logging_info.setText("Logging");
        logging_info.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                logging_infoActionPerformed(evt);
            }
        });
        info_menu.add(logging_info);

        jMenu1.add(info_menu);
        jMenu1.add(jSeparator2);

        onCloseMenu.setText("On Close");

        menuHide.setText("Hide");
        menuHide.setActionCommand("Hideme");
        onCloseMenu.add(menuHide);

        menuExit.setText("Exit");
        menuExit.setActionCommand("Exitme");
        menuExit.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                menuExitItemStateChanged(evt);
            }
        });
        onCloseMenu.add(menuExit);

        jMenu1.add(onCloseMenu);

        aboutMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.SHIFT_MASK));
        aboutMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/about_menu.png"))); // NOI18N
        aboutMenu.setText("About");
        aboutMenu.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                aboutMenuActionPerformed(evt);
            }
        });
        jMenu1.add(aboutMenu);

        Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit_menu.png"))); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ExitActionPerformed(evt);
            }
        });
        jMenu1.add(Exit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(12, 12, 12)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel5)
                                    .add(jLabel6))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(loc_Ip_Port, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 117, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(layout.createSequentialGroup()
                                        .add(public_Ip_Port, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 133, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(refreshBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(jLabel10)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(serverStatus, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 105, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(layout.createSequentialGroup()
                                        .add(jLabel12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(activeUsers, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 74, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                            .add(layout.createSequentialGroup()
                                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 440, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(0, 0, Short.MAX_VALUE)))
                        .add(0, 12, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel1)
                                    .add(portNumber))
                                .add(18, 18, 18)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(portField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 88, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(jLabel3))
                                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 124, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(mutexCheckbox))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, StartBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, StopBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(21, 21, 21))))
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel8)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(date_now, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(time_now, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel10)
                            .add(serverStatus))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel12)
                            .add(activeUsers, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel5)
                            .add(loc_Ip_Port, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel6)
                            .add(public_Ip_Port, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(refreshBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(12, 12, 12)
                        .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(StartBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 54, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(2, 2, 2)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(portField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel3)))
                            .add(portNumber, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(mutexCheckbox))
                    .add(StopBtn, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 279, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(date_now)
                    .add(jLabel8)
                    .add(time_now))
                .add(9, 9, 9))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void initComponentsNew()
    {
        menugroup = new ButtonGroup();
        menugroup.add(menuHide);
        menugroup.add(menuExit);
        SystemTray = SystemTray.getSystemTray();
        PopupMenu = new PopupMenu();
        showItem = new MenuItem("Socketty");
        exitItem = new MenuItem("Exit");
        listeningTo = new MenuItem("");
        statusNow = new MenuItem("Status = Not Running ...");

        showItem.setFont(SystemFontLoader.getSegoe_UI_SemiBoldFont().deriveFont(0, 11f));
        exitItem.setFont(SystemFontLoader.getSegoe_UI_SemiBoldFont().deriveFont(0, 11f));
        listeningTo.setFont(SystemFontLoader.getSegoe_UI_SemiBoldFont().deriveFont(0, 11f));
        statusNow.setFont(SystemFontLoader.getSegoe_UI_SemiBoldFont().deriveFont(0, 11f));
        URL url = getClass().getResource("/icons/tray_icon.png");
        ico = Toolkit.getDefaultToolkit().getImage(url);
        trayIcon = new TrayIcon(ico, "Socketty (Not Running)", PopupMenu);
        //adjust to default size as per system recommendation
        trayIcon.setImageAutoSize(true);
        PopupMenu.add(statusNow);
        PopupMenu.addSeparator();
        PopupMenu.add(showItem);
        PopupMenu.addSeparator();
        PopupMenu.add(exitItem);

        showItem.addActionListener((java.awt.event.ActionEvent evt) ->
        {
            showItemActionPerformed(evt);
        });

        exitItem.addActionListener((ActionEvent evt) ->
        {
            exitItemActionPerformed(evt);
        });

        trayIcon.addActionListener((ActionEvent evt) ->
        {
            trayIconActionPerformed(evt);
        });

        verticalScrollBarMaximumValue = jScrollPane1.getVerticalScrollBar().getMaximum();
        jScrollPane1.getVerticalScrollBar().addAdjustmentListener(e ->
        {
            if((verticalScrollBarMaximumValue - e.getAdjustable().getMaximum()) == 0)
            {
                return;
            }
            e.getAdjustable().setValue(e.getAdjustable().getMaximum());
            verticalScrollBarMaximumValue = jScrollPane1.getVerticalScrollBar().getMaximum();
        });

        try
        {
            SystemTray.add(trayIcon);
        }
        catch(AWTException e)
        {
            Logger.getLogger(ServerMain.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    private void StartBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_StartBtnActionPerformed
    {//GEN-HEADEREND:event_StartBtnActionPerformed
        boolean isBindException, isIOException, isIllegalArgument, isNullPointerException;
        isBindException = isIOException = isIllegalArgument = isNullPointerException = false;
        try
        {
            port = Integer.parseInt(portField.getText());
            ss = new ServerSocket(port);
        }
        catch(NumberFormatException e)
        {
            if(portField.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Port cannot be left Empty", "Port Error", JOptionPane.WARNING_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Port can only be a Number", "Input Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(BindException b) //for serversocket object
        {
            isBindException = true; //setted flag to true (only if ocurred)
            JOptionPane.showMessageDialog(this, "Port Already being used by some other application", "Port Already Occupied", JOptionPane.WARNING_MESSAGE);
        }
        catch(IOException e)
        {
            isIOException = true;
            JOptionPane.showMessageDialog(this, "Exception ocurred in I/O of the program\nwhile making connection request", "I/O Error", JOptionPane.WARNING_MESSAGE);
            System.out.println("IOException ocurred");
        }
        catch(IllegalArgumentException e)
        {
            isIllegalArgument = true;
            //JOptionPane.showMessageDialog(this, "Port isn't in the range specified", "Value Error", JOptionPane.WARNING_MESSAGE);
        }
        catch(NullPointerException e)
        {
            isNullPointerException = true;
        }

        if(port < 10)
        {
            JOptionPane.showMessageDialog(this, "Port isn't in the range specified", "Value Error", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            if(isBindException | isIOException | isIllegalArgument)
            {
                //DO nothing LOL, just for keeping the fact of executing nothing until user's input
            }
            if(!isBindException && !isIOException && !isIllegalArgument)
            {
                //enabling btn for use now
                refreshBtn.setEnabled(true);
                StartBtn.setEnabled(false);
                StopBtn.setEnabled(true);
                portField.setEnabled(false);
                serverStatus.setForeground(new Color(9, 110, 35));
                serverStatus.setText("Server is Running...");
                loc_Ip_Port.setText(new IpAPI().loc_Ip() + " : " + port);
                CurrStatus.append("\n[" + forStamping.format(LocalDateTime.now()) + "]  Success, the Server is now listening on the port " + port + ".....");
                try
                {
                    //calling the execute method for thread creation
                    execute();
                    if(SystemTray.isSupported())
                    {
                        trayIcon.setToolTip("Socketty (Running Port :: " + port + ")");
                        statusNow.setLabel("Status :: Running ...");
                        listeningTo.setLabel("Listening on Port :: " + port);
                        PopupMenu.insert(listeningTo, 1);
                    }
                }
                catch(Exception ex)
                {
                    Logger.getLogger(ServerMain.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_StartBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_refreshBtnActionPerformed
    {//GEN-HEADEREND:event_refreshBtnActionPerformed
        loc_Ip_Port.setText(new IpAPI().loc_Ip() + " : " + port);
        IpAPI obj = new IpAPI();
        obj.start();
        String ip = obj.pub_Ip();
        if(ip.equalsIgnoreCase("Offline"))
        {
            public_Ip_Port.setText("Offline");
        }

        else
        {
            public_Ip_Port.setText(ip + " : " + port);
        }
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void loc_Ip_PortAncestorAdded(javax.swing.event.AncestorEvent evt)//GEN-FIRST:event_loc_Ip_PortAncestorAdded
    {//GEN-HEADEREND:event_loc_Ip_PortAncestorAdded
        if(isAlreadyLoaded == false)
        {
            try
            {
                if(SystemTray.isSupported())
                {
                    ins = new FileInputStream(config_file);
                    properties.load(ins);
                    String exitOption = properties.getProperty("On_Exit_Action");
                    ins.close();
                    System.out.println(exitOption);
                    if(exitOption.equals("Hide"))
                    {
                        menuHide.setSelected(true);
                    }
                    if(exitOption.equals("Exit"))
                    {
                        menuExit.setSelected(true);
                    }
                    if(!exitOption.equals("Hide") && !exitOption.equals("Exit"))
                    {
                        return;
                    }
                }
            }
            catch(IOException e)
            {
                Logger.getLogger(ServerMain.class.getName()).log(Level.SEVERE, null, e);
            }
            loc_Ip_Port.setText(new IpAPI().loc_Ip());
            IpAPI obj = new IpAPI();
            obj.start();
            String ip = obj.pub_Ip();
            if(ip.equalsIgnoreCase("Offline"))
            {
                public_Ip_Port.setText("Offline");
            }
            else
            {
                public_Ip_Port.setText(ip);
            }
        }
        isAlreadyLoaded = true;
    }//GEN-LAST:event_loc_Ip_PortAncestorAdded

    private void StopBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_StopBtnActionPerformed
    {//GEN-HEADEREND:event_StopBtnActionPerformed
        Object choice[] =
        {
            "Yes", "No"
        };
        // Object defaultchoice = choice[0];
        //can also be specified as an Object
        int selectedValue = JOptionPane.showOptionDialog(
                rootPane,
                "Stopping can cause any client[s] connected\n"
                + "to this server to halt the connection and\n"
                + "disconnect ...!",
                "Confirm Stop Server",
                // JOptionPane.YES_NO_OPTION,
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                choice,
                choice[0]
        );

        if(selectedValue == JOptionPane.YES_OPTION)
        {
            try
            {
                run.interrupt();
                ss.close();
                out = new FileOutputStream(config_file);
                properties.replace("Last_known_port", String.valueOf(port));
                properties.store(out, "DON'T TRY TO MODIFY THESE FIELDS");
                out.close();

                if(SystemTray.isSupported())
                {
                    trayIcon.setToolTip("Socketty (Not Running)");
                    PopupMenu.remove(listeningTo);
                    statusNow.setLabel("Status :: Not Running ...");
                }
                isReadyToClose = true;
                portField.setEnabled(true);
                loc_Ip_Port.setText(new IpAPI().loc_Ip());
                StartBtn.setEnabled(true);
                serverStatus.setForeground(Color.red);
                serverStatus.setText("Offline");
                StopBtn.setEnabled(false);
                CurrStatus.append("\n[" + forStamping.format(LocalDateTime.now()) + "]  Server Stopped Succesfully !\n");
                CurrStatus.append("----------------------------------------------------------------------------------------------------------");
            }
            catch(IOException ex)
            {
                Logger.getLogger(ServerMain.class.getName()).log(Level.SEVERE, null, ex);
                StopBtn.setEnabled(true);
            }
        }
        else if(selectedValue == JOptionPane.NO_OPTION)
        {
            System.out.println("NO pressed");
        }
        else if(selectedValue == JOptionPane.CLOSED_OPTION)
        {
            System.out.println("Cancelled stop dialog");
        }
    }//GEN-LAST:event_StopBtnActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        try
        {
            if(!SystemTray.isSupported())
            {
                ClosingTask();
                SystemTray.remove(trayIcon);
            }
            if(SystemTray.isSupported())
            {
                ins = new FileInputStream(config_file);
                properties.load(ins);
                String exitOption = properties.getProperty("On_Exit_Action");
                ins.close();
                System.out.println(exitOption);
                if(exitOption.equals("Hide"))
                {
                    this.setVisible(false);
                }
                if(exitOption.equals("Exit"))
                {
                    ClosingTask();
                }
                if(!exitOption.equals("Hide") && !exitOption.equals("Exit"))
                {
                    String options[] = new String[]
                    {
                        "Hide", "Exit"
                    };
                    int response = JOptionPane.showOptionDialog(
                            this,
                            "Do you really wish to Exit or Just Hide ?",
                            "Exit",
                            JOptionPane.DEFAULT_OPTION,
                            JOptionPane.QUESTION_MESSAGE,
                            null,
                            options,
                            options[0]);

                    if(response == 0)
                    {
                        out = new FileOutputStream(config_file, false);
                        properties.replace("On_Exit_Action", options[response]);
                        properties.store(out, "DON'T TRY TO MODIFY THESE FIELDS");
                        out.close();
                        this.setVisible(false);
                    }
                    if(response == 1)
                    {
                        out = new FileOutputStream(config_file, false);
                        properties.replace("On_Exit_Action", options[response]);
                        properties.store(out, "DON'T TRY TO MODIFY THESE FIELDS");
                        out.close();
                        ClosingTask();
                    }
                }
            }
        }
        catch(Exception e)
        {
            Logger.getLogger(ServerMain.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_formWindowClosing

    private void aboutMenuActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_aboutMenuActionPerformed
    {//GEN-HEADEREND:event_aboutMenuActionPerformed
        new about_form().setVisible(true);
    }//GEN-LAST:event_aboutMenuActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ExitActionPerformed
    {//GEN-HEADEREND:event_ExitActionPerformed
        ClosingTask();
    }//GEN-LAST:event_ExitActionPerformed

    private void logging_infoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_logging_infoActionPerformed
    {//GEN-HEADEREND:event_logging_infoActionPerformed
        JOptionPane.showMessageDialog(
                rootPane,
                "Socketty has the ability to log all the history i.e things\n"
                + "happened during active sessions and to save them in a text\n"
                + "file named by the date on which the program got executed\n"
                + "and this file saved under logs directory, You are requested\n"
                + "to read all the Instructions and don't perform any unEthical\n"
                + "actions which can made this program brittle in working !!", "Information",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_logging_infoActionPerformed

    private void mutexCheckboxItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_mutexCheckboxItemStateChanged
    {//GEN-HEADEREND:event_mutexCheckboxItemStateChanged
        if(!mutexCheckbox.isSelected())
        {
            mutexCheckbox.setEnabled(false);
            new MutexDeployer().MutexDestroyer();
        }
    }//GEN-LAST:event_mutexCheckboxItemStateChanged

    private void menuExitItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_menuExitItemStateChanged
    {//GEN-HEADEREND:event_menuExitItemStateChanged
        try
        {
            String command = menugroup.getSelection().getActionCommand();
            if(command != null)
            {
                if(command.equals("Hideme"))
                {
                    out = new FileOutputStream(config_file, false);
                    properties.replace("On_Exit_Action", "Hide");
                    properties.store(out, "DON'T TRY TO MODIFY THESE FIELDS");
                    out.close();
                }
                else if(command.equals("Exitme"))
                {
                    out = new FileOutputStream(config_file, false);
                    properties.replace("On_Exit_Action", "Exit");
                    properties.store(out, "DON'T TRY TO MODIFY THESE FIELDS");
                    out.close();
                }
            }
        }
        catch(Exception e)
        {
            System.out.println("Nothing Selected !!");
        }
    }//GEN-LAST:event_menuExitItemStateChanged

    private void portFieldAncestorAdded(javax.swing.event.AncestorEvent evt)//GEN-FIRST:event_portFieldAncestorAdded
    {//GEN-HEADEREND:event_portFieldAncestorAdded
        portField.setText(properties.getProperty("Last_known_port"));
    }//GEN-LAST:event_portFieldAncestorAdded

    private void showItemActionPerformed(ActionEvent evt)
    {
        this.setVisible(true);
        this.revalidate();
    }

    private void exitItemActionPerformed(ActionEvent evt)
    {
        this.setVisible(true);
        ClosingTask();
    }

    private void trayIconActionPerformed(ActionEvent evt)
    {
        this.setVisible(true);
        this.revalidate();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() ->
        {
            //Generate Mutex Evertime During running operation
            new MutexDeployer().MutexGenerator();
            new ServerMain().setVisible(true);
        });
    }

    private SystemTray SystemTray;
    private PopupMenu PopupMenu;
    private MenuItem showItem;
    private MenuItem exitItem;
    private MenuItem statusNow;
    private MenuItem listeningTo;
    private ButtonGroup menugroup;
    private Image ico;
    private TrayIcon trayIcon;
    private DateTimeFormatter forStamping = DateTimeFormatter.ofPattern("HH:mm:ss");
    private DateTimeFormatter forlog = DateTimeFormatter.ofPattern("dd-MMMM-yyyy");
    private File logDir = new File("logs");
    private File dataDir = new File("data");
    private File config_file = new File("config.properties");
    private String logFileName = "Server_" + forlog.format(LocalDateTime.now()) + "_LOG.txt";
    private File logFile = new File(logDir + File.separator + logFileName);
    private BufferedWriter logFileWriter;
    private FileOutputStream out;
    private FileInputStream ins;
    private ServerSocket ss;
    private Thread run;
    private int verticalScrollBarMaximumValue;
    private Properties properties;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea CurrStatus;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JButton StartBtn;
    private javax.swing.JButton StopBtn;
    private javax.swing.JMenuItem aboutMenu;
    private javax.swing.JComboBox<String> activeUsers;
    private javax.swing.JLabel date_now;
    private javax.swing.JMenu info_menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField loc_Ip_Port;
    private javax.swing.JMenuItem logging_info;
    private javax.swing.JCheckBoxMenuItem menuExit;
    private javax.swing.JCheckBoxMenuItem menuHide;
    private javax.swing.JCheckBox mutexCheckbox;
    private javax.swing.JMenu onCloseMenu;
    private javax.swing.JTextField portField;
    private javax.swing.JLabel portNumber;
    private javax.swing.JTextField public_Ip_Port;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JLabel serverStatus;
    private javax.swing.JLabel time_now;
    // End of variables declaration//GEN-END:variables

    private void dirVerifier()
    {
        String default_header = "\t\t\t\t\t\t\t\t\t\t***DO NOT EDIT OR MODIFY THIS FILE OF YOUR OWN***\n\n"
                + "This file is auto generated by default through CoreServer"
                + " Application (Author: Neeraj, License MIT's License)\n" + "File created on: ["
                + DateTimeFormatter.ofPattern("hh:mm:ss a dd-MMMM-yyyy").format(LocalDateTime.now())
                + "]\nSince all the data here included in this file will get generated by default EVERYTIME we open "
                + "and close the Application (for logging purposes),Two types of record formatters are used here as >> and -- N.B\n\n"
                + "1. Firstly  >> is used as a formatting char only, and to distinguish the program opening and closing sessions.\n"
                + "2. Secondly -- means of one server deployment and then disengagement, as many consecutive deplys and disengmnts"
                + " can be done one after the other, this file gets auto incremented/appends the records each and everytime any activity is"
                + "done on the server which is getting logged into Console and then dumping it into this log file for "
                + "later Activity Assesment purposes ,You're requested to keep your time in sync as this software uses and logs "
                + "the same using underlying machine's time, if there is any discrepency in the system's time the loging will get "
                + "cluttered, for more info visit the developer's site to resolve this problem !!\n\n"
                + ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>EXECUTION-STARTS>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n\n";
        try
        {
            CurrStatus.append("[" + forStamping.format(LocalDateTime.now()) + "]  Checking the required directories exists ??...");
            if(logDir.exists())
            {
                CurrStatus.append("\n[" + forStamping.format(LocalDateTime.now()) + "]  Directory /logs already exists !");
                File temp[] = logDir.listFiles();
                if(temp.length > 0)
                {
                    if(logFile.exists())
                    {
                        CurrStatus.append("\n[" + forStamping.format(LocalDateTime.now()) + "]  Today's Log file already exists ...!");
                    }
                    //can execute if todays file isn't present among others
                    else if(!logFile.exists())
                    {
                        logFile.createNewFile();
                        logFileWriter = new BufferedWriter(new FileWriter(logFile, true));
                        logFileWriter.write(default_header);
                        logFileWriter.close();
                        CurrStatus.append("\n[" + forStamping.format(LocalDateTime.now()) + "]  Today's Log file creation: SUCCESS");
                    }
                }
                if(temp.length == 0)
                {
                    CurrStatus.append("\n[" + forStamping.format(LocalDateTime.now()) + "]  No special named file[s] found in directory /logs");
                    logFile.createNewFile();
                    logFileWriter = new BufferedWriter(new FileWriter(logFile, true));
                    logFileWriter.write(default_header);
                    logFileWriter.close();
                    CurrStatus.append("\n[" + forStamping.format(LocalDateTime.now()) + "]  Today's Log file creation: SUCCESS");
                }
            }
            if(!logDir.exists())
            {
                logDir.mkdir();
                CurrStatus.append("\n[" + forStamping.format(LocalDateTime.now()) + "]  Directory /logs creation: SUCCESS");
                logFile.createNewFile();
                logFileWriter = new BufferedWriter(new FileWriter(logFile, true));
                logFileWriter.write(default_header);
                logFileWriter.close();
                CurrStatus.append("\n[" + forStamping.format(LocalDateTime.now()) + "]  Today's Log file creation: SUCCESS");
            }

            if(config_file.exists())
            {
                ins = new FileInputStream(config_file);
                properties = new Properties();
                properties.load(ins);
                ins.close();
            }
            if(!config_file.exists())
            {
                config_file.createNewFile();
                out = new FileOutputStream(config_file);
                properties = new Properties();
                //AN extra newLine feed char is always reserved if you want custom Input from Keyboard
                properties.put("On_Exit_Action", "");
                properties.put("Last_known_port", "");
                properties.store(out, "DON'T TRY TO MODIFY THESE FIELDS");
                out.close();

                ins = new FileInputStream(config_file);
                properties.load(ins);
                ins.close();
            }
            /**
             * Code for making new folder named data (will cause the client to freeze if not
             * properly used, as all the data from each other will reside here only !!
             */
            if(dataDir.exists())
            {
                CurrStatus.append("\n[" + forStamping.format(LocalDateTime.now()) + "]  Directory /data already exists ..!");
                CurrStatus.append("\n[" + forStamping.format(LocalDateTime.now()) + "]  Checking if the Directory /data empty ? ");
                /**
                 * This above method deletes the old files in the directory named Data(if exists) in
                 * the Project's root path or AT the base directory of Main Executable file in a
                 * directory named data, and then replaces it with the new Current session's file
                 * for keeping a list of data in session for Assessment purposes
                 */
                File f[] = dataDir.listFiles();
                if(f.length == 0)
                {
                    CurrStatus.append("\n[" + forStamping.format(LocalDateTime.now()) + "]  Directory /data was already clean ...!");
                }
                else if(f.length > 0)
                {
                    CurrStatus.append("\n[" + forStamping.format(LocalDateTime.now()) + "]  Detected " + f.length + " files in directory /data");
                    CurrStatus.append("\n[" + forStamping.format(LocalDateTime.now()) + "]  Deleting " + f.length + " files.... in directory /data");
                    for(File fs : dataDir.listFiles())
                    {
                        fs.delete();
                    }
                    CurrStatus.append("\n[" + forStamping.format(LocalDateTime.now()) + "]  Deletion Successfull");
                }
            }
            if(!dataDir.exists())
            {
                CurrStatus.append("\n[" + forStamping.format(LocalDateTime.now()) + "]  Directory /data not Exists ...!!");
                dataDir.mkdir();//Execute the above object
                //Failure of creation of above folder in the root path can cause
                //null pointer exception -------!!!
                CurrStatus.append("\n[" + forStamping.format(LocalDateTime.now()) + "]  Directory named " + dataDir.getPath() + " creation: SUCCESS");

            }
        }
        catch(IOException ex)
        {
            Logger.getLogger(ServerMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void execute() throws Exception
    {
        isReadyToClose = false;
        //Calling start Method
        Method.setClients(new ArrayList<>());
        /**
         * Will Update The fields and initialize a new Thread (Runnable) for each incoming CLient
         * request by passing it to the this-->Method-->Message-->Client Class.
         * for above details see the Project's Hierarchy.
         */
        run = new Thread(() ->
        {
            try
            {
                Method.compntPasser(CurrStatus, activeUsers);
                while(true)
                {
                    new Client(ss.accept());
                }

            }
            catch(Exception e)
            {
//                JOptionPane.showMessageDialog(
//                        ServerMain.this,
//                        "Server Closed forcefully in during mid scanning\nof incoming client requests !!",
//                        "Error", JOptionPane.WARNING_MESSAGE);
            }
        });

        run.start();
    }

    /**
     * Display the closing option before Calling closing window(frame)
     *
     * @return Nothing XD
     */
    private void ClosingTask()
    {
        Object choice[] =
        {
            "Yes", "No"
        };
        // Object defaultchoice = choice[0];
        //can also be specified as an Object
        int selectedValue = JOptionPane.showOptionDialog(
                rootPane,
                "Exiting will close this server's session ?",
                "Confirm",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                choice,
                choice[0]
        );

        if(selectedValue == JOptionPane.YES_OPTION)
        {
            if(ss != null)//server was initialised somewhat before
            {
                if(!ss.isClosed())//server is running still
                {
                    StopBtn.doClick();//calling to stop the server
                    if(isReadyToClose == true)
                    {
                        logFooter();
                        SystemTray.remove(trayIcon);
                        System.exit(0);
                    }
                }
                else if(ss.isClosed())
                {
                    logFooter();
                    SystemTray.remove(trayIcon);
                    System.exit(0);
                }
            }
            else if(ss == null)
            {
                logFooter();
                SystemTray.remove(trayIcon);
                System.exit(0);
            }
        }
//        else if(selectedValue == JOptionPane.NO_OPTION)
//        {
//            System.out.println("Not exiting");
//        }
//        else if(selectedValue == JOptionPane.CLOSED_OPTION)
//        {
//            System.out.println("Cancelled");
//        }
    }

    private void logFooter()
    {
        try
        {
            logFileWriter = new BufferedWriter(new FileWriter(logFile, true));
            logFileWriter.write(CurrStatus.getText() + "\n\nFile Last Opened/Modified : "
                    + DateTimeFormatter.ofPattern("HH:mm:ss").format(LocalDateTime.now())
                    + " Dated : " + DateTimeFormatter.ofPattern("dd/MMMM/yyyy").format(LocalDateTime.now())
                    + "\n-------------------------------------------------[Exited]-------------------------------------------------"
                    + "\n\n>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n\n");
            logFileWriter.close();
        }
        catch(IOException ex)
        {
            Logger.getLogger(ServerMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
